All:eserial

eserial: linux_serial_signal_interrupt.cpp
	g++ -Wall -Wextra -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align \
	-Wconversion linux_serial_signal_interrupt.cpp -o eserial 
	

clean: 
	rm eserial










